const proto: any = Array.prototype;
const join: any = proto.join;

console.log("is array:", Array.isArray(proto), proto.length);
console.log("object proto:", Object.getPrototypeOf(proto) === Object.prototype);
console.log("own keys:", Object.keys(proto).length, Object.values(proto).length, Object.entries(proto).length);
console.log("reflect:", Reflect.ownKeys(proto).includes("length"), Reflect.getOwnPropertyDescriptor(proto, "length") !== undefined);
const lengthDescriptor: any = Reflect.getOwnPropertyDescriptor(proto, "length");
console.log("length descriptor:", lengthDescriptor.value, lengthDescriptor.writable, lengthDescriptor.enumerable, lengthDescriptor.configurable, Reflect.set(proto, "length", 1), proto.length);
const map: any = proto.map;
const mapDescriptor: any = Reflect.getOwnPropertyDescriptor(proto, "map");
console.log("method metadata:", map.name, map.length, Reflect.has(map, "prototype"), mapDescriptor.writable, mapDescriptor.enumerable, mapDescriptor.configurable);
const nameDescriptor: any = Reflect.getOwnPropertyDescriptor(map, "name");
const arityDescriptor: any = Reflect.getOwnPropertyDescriptor(map, "length");
console.log("function descriptors:", nameDescriptor.writable, nameDescriptor.enumerable, nameDescriptor.configurable, arityDescriptor.writable, arityDescriptor.enumerable, arityDescriptor.configurable);
const unscopables: any = (Array.prototype as any)[Symbol.unscopables];
console.log("unscopables:", typeof unscopables, Object.getPrototypeOf(unscopables), Object.keys(unscopables).sort().join("|"), unscopables.at, unscopables.values, unscopables.reverse);
const symbolKeys: symbol[] = Object.getOwnPropertySymbols(Array.prototype);
const iteratorSymbolDescriptor: any = Object.getOwnPropertyDescriptor(Array.prototype, Symbol.iterator);
const unscopablesDescriptor: any = Object.getOwnPropertyDescriptor(Array.prototype, Symbol.unscopables);
console.log("symbols:", symbolKeys.length, symbolKeys[0] === Symbol.iterator, symbolKeys[1] === Symbol.unscopables, symbolKeys[0].description + "|" + symbolKeys[1].description);
console.log("symbol descriptors:", iteratorSymbolDescriptor.value === proto.values, iteratorSymbolDescriptor.writable, iteratorSymbolDescriptor.enumerable, iteratorSymbolDescriptor.configurable, unscopablesDescriptor.value === unscopables, unscopablesDescriptor.writable, unscopablesDescriptor.enumerable, unscopablesDescriptor.configurable);
const every: any = proto.every;
console.log("delete name:", Reflect.deleteProperty(every, "name"), Object.hasOwn(every, "name"));
console.log("redefine:", Reflect.defineProperty(every, "name", { value: "all" }), Reflect.defineProperty(every, "length", { value: 3 }), every.name, every.length);
console.log("method:", Reflect.apply(join, ["a", "b"], ["-"]));
