const proto: any = Array.prototype;
const join: any = proto.join;

console.log("is array:", Array.isArray(proto), proto.length);
console.log("object proto:", Object.getPrototypeOf(proto) === Object.prototype);
console.log("own keys:", Object.keys(proto).length, Object.values(proto).length, Object.entries(proto).length);
console.log("reflect:", Reflect.ownKeys(proto).includes("length"), Reflect.getOwnPropertyDescriptor(proto, "length") !== undefined);
const ownNames: string[] = Object.getOwnPropertyNames(Array.prototype);
const reflectOwnKeys: string[] = Reflect.ownKeys(Array.prototype);
const allDescriptors: any = Object.getOwnPropertyDescriptors(Array.prototype);
console.log("own names:", ownNames.length, ownNames[0], ownNames.includes("constructor"), ownNames.includes("map"), ownNames.includes("valueOf"));
console.log("reflect own names:", reflectOwnKeys.length, reflectOwnKeys[0], reflectOwnKeys.includes("constructor"), reflectOwnKeys.includes("map"), reflectOwnKeys.includes("valueOf"));
const aliasOwnNames: string[] = Object.getOwnPropertyNames(proto);
const aliasReflectOwnKeys: string[] = Reflect.ownKeys(proto);
console.log("alias own names:", aliasOwnNames.length, aliasOwnNames.includes("constructor"), aliasOwnNames.includes("map"), aliasOwnNames.includes("valueOf"), aliasReflectOwnKeys.length, aliasReflectOwnKeys.includes("valueOf"));
const aliasAllDescriptors: any = Object.getOwnPropertyDescriptors(proto);
const aliasValueOfDescriptor: any = Object.getOwnPropertyDescriptor(proto, "valueOf");
console.log("alias descriptors:", Object.keys(aliasAllDescriptors).length, Object.hasOwn(aliasAllDescriptors, "valueOf"), aliasValueOfDescriptor === undefined);
console.log("all descriptors:", Object.keys(allDescriptors).length, allDescriptors["length"].value, allDescriptors.constructor.value === Array, allDescriptors.map.value === proto.map, Object.hasOwn(allDescriptors, "valueOf"));
const staticMapDescriptor: any = Object.getOwnPropertyDescriptor(Array.prototype, "map");
const staticConstructorDescriptor: any = Reflect.getOwnPropertyDescriptor(Array.prototype, "constructor");
const staticValueOfDescriptor: any = Object.getOwnPropertyDescriptor(Array.prototype, "valueOf");
console.log("static string descriptors:", staticMapDescriptor.value === proto.map, staticMapDescriptor.writable, staticMapDescriptor.enumerable, staticMapDescriptor.configurable, staticConstructorDescriptor.value === Array, staticConstructorDescriptor.writable, staticConstructorDescriptor.enumerable, staticConstructorDescriptor.configurable, staticValueOfDescriptor === undefined);
console.log("own checks:", Object.hasOwn(Array.prototype, "map"), Object.hasOwn(Array.prototype, "valueOf"), proto.hasOwnProperty("constructor"), proto.propertyIsEnumerable("map"), Reflect.has(Array.prototype, "map"), Reflect.has(Array.prototype, "valueOf"));
console.log("symbol checks:", Object.hasOwn(proto, Symbol.iterator), Object.hasOwn(proto, Symbol.unscopables), Object.hasOwn([], Symbol.iterator), Reflect.has(proto, Symbol.iterator), Reflect.has([], Symbol.iterator), Reflect.has(Object.prototype, Symbol.iterator));
const lengthDescriptor: any = Reflect.getOwnPropertyDescriptor(proto, "length");
console.log("length descriptor:", lengthDescriptor.value, lengthDescriptor.writable, lengthDescriptor.enumerable, lengthDescriptor.configurable, Reflect.set(proto, "length", 1), proto.length);
const map: any = proto.map;
const mapDescriptor: any = Reflect.getOwnPropertyDescriptor(proto, "map");
console.log("method metadata:", map.name, map.length, Reflect.has(map, "prototype"), mapDescriptor.writable, mapDescriptor.enumerable, mapDescriptor.configurable);
const nameDescriptor: any = Reflect.getOwnPropertyDescriptor(map, "name");
const arityDescriptor: any = Reflect.getOwnPropertyDescriptor(map, "length");
console.log("function descriptors:", nameDescriptor.writable, nameDescriptor.enumerable, nameDescriptor.configurable, arityDescriptor.writable, arityDescriptor.enumerable, arityDescriptor.configurable);
const unscopables: any = (Array.prototype as any)[Symbol.unscopables];
console.log("unscopables:", typeof unscopables, Object.getPrototypeOf(unscopables), Object.keys(unscopables).sort().join("|"), unscopables.at, unscopables.values, unscopables.reverse);
const symbolKeys: symbol[] = Object.getOwnPropertySymbols(Array.prototype);
const aliasSymbolKeys: symbol[] = Object.getOwnPropertySymbols(proto);
const iteratorSymbolDescriptor: any = Object.getOwnPropertyDescriptor(Array.prototype, Symbol.iterator);
const unscopablesDescriptor: any = Object.getOwnPropertyDescriptor(Array.prototype, Symbol.unscopables);
const aliasIteratorSymbolDescriptor: any = Object.getOwnPropertyDescriptor(proto, Symbol.iterator);
const aliasUnscopablesDescriptor: any = Reflect.getOwnPropertyDescriptor(proto, Symbol.unscopables);
const reflectIteratorDescriptor: any = Reflect.getOwnPropertyDescriptor(Array.prototype, Symbol.iterator);
const reflectUnscopablesDescriptor: any = Reflect.getOwnPropertyDescriptor(Array.prototype, Symbol.unscopables);
console.log("symbols:", symbolKeys.length, symbolKeys[0] === Symbol.iterator, symbolKeys[1] === Symbol.unscopables, symbolKeys[0].description + "|" + symbolKeys[1].description);
console.log("alias symbols:", aliasSymbolKeys.length, aliasSymbolKeys[0] === Symbol.iterator, aliasSymbolKeys[1] === Symbol.unscopables, aliasSymbolKeys[0].description + "|" + aliasSymbolKeys[1].description);
console.log("symbol descriptors:", iteratorSymbolDescriptor.value === proto.values, iteratorSymbolDescriptor.writable, iteratorSymbolDescriptor.enumerable, iteratorSymbolDescriptor.configurable, unscopablesDescriptor.value === unscopables, unscopablesDescriptor.writable, unscopablesDescriptor.enumerable, unscopablesDescriptor.configurable);
console.log("alias symbol descriptors:", aliasIteratorSymbolDescriptor.value === proto.values, aliasIteratorSymbolDescriptor.writable, aliasIteratorSymbolDescriptor.enumerable, aliasIteratorSymbolDescriptor.configurable, aliasUnscopablesDescriptor.value === unscopables, aliasUnscopablesDescriptor.writable, aliasUnscopablesDescriptor.enumerable, aliasUnscopablesDescriptor.configurable);
console.log("reflect symbol descriptors:", reflectIteratorDescriptor.value === iteratorSymbolDescriptor.value, reflectIteratorDescriptor.writable, reflectIteratorDescriptor.enumerable, reflectIteratorDescriptor.configurable, reflectUnscopablesDescriptor.value === unscopablesDescriptor.value, reflectUnscopablesDescriptor.writable, reflectUnscopablesDescriptor.enumerable, reflectUnscopablesDescriptor.configurable);
const every: any = proto.every;
console.log("delete name:", Reflect.deleteProperty(every, "name"), Object.hasOwn(every, "name"));
console.log("redefine:", Reflect.defineProperty(every, "name", { value: "all" }), Reflect.defineProperty(every, "length", { value: 3 }), every.name, every.length);
console.log("method:", Reflect.apply(join, ["a", "b"], ["-"]));
