import { EventEmitter, on } from "node:events";

async function collect(iterator: any, output: string[]): Promise<string> {
    for await (const item of iterator) {
        await Promise.resolve(item);
        const first = item[0];
        await Promise.resolve(first);
        let second: string;
        second = first + "-second";
        await Promise.resolve(second);
        const third = second + "-third";
        await Promise.resolve(third);
        const fourth = third + "-fourth";
        await Promise.resolve(fourth);
        const fifth = fourth + "-fifth";
        await Promise.resolve(fifth);
        const sixth = fifth + "-sixth";
        await Promise.resolve(sixth);
        const seventh = sixth + "-seventh";
        await Promise.resolve(seventh);
        const eighth = seventh + "-eighth";
        await Promise.resolve(eighth);
        const ninth = eighth + "-ninth";
        await Promise.resolve(ninth);
        const tenth = ninth + "-tenth";
        await Promise.resolve(tenth);
        const eleventh = tenth + "-eleventh";
        await Promise.resolve(eleventh);
        const twelfth = eleventh + "-twelfth";
        await Promise.resolve(twelfth);
        const thirteenth = twelfth + "-thirteenth";
        await Promise.resolve(thirteenth);
        const fourteenth = thirteenth + "-fourteenth";
        await Promise.resolve(fourteenth);
        const fifteenth = fourteenth + "-fifteenth";
        await Promise.resolve(fifteenth);
        const sixteenth = fifteenth + "-sixteenth";
        await Promise.resolve(sixteenth);
        const seventeenth = sixteenth + "-seventeenth";
        await Promise.resolve(seventeenth);
        const eighteenth = seventeenth + "-eighteenth";
        await Promise.resolve(eighteenth);
        const nineteenth = eighteenth + "-nineteenth";
        await Promise.resolve(nineteenth);
        const twentieth = nineteenth + "-twentieth";
        await Promise.resolve(twentieth);
        const twentyFirst = twentieth + "-twenty-first";
        await Promise.resolve(twentyFirst);
        const twentySecond = twentyFirst + "-twenty-second";
        await Promise.resolve(twentySecond);
        const twentyThird = twentySecond + "-twenty-third";
        await Promise.resolve(twentyThird);
        const twentyFourth = twentyThird + "-twenty-fourth";
        await Promise.resolve(twentyFourth);
        const twentyFifth = twentyFourth + "-twenty-fifth";
        await Promise.resolve(twentyFifth);
        const twentySixth = twentyFifth + "-twenty-sixth";
        await Promise.resolve(twentySixth);
        const twentySeventh = twentySixth + "-twenty-seventh";
        await Promise.resolve(twentySeventh);
        const twentyEighth = twentySeventh + "-twenty-eighth";
        await Promise.resolve(twentyEighth);
        const twentyNinth = twentyEighth + "-twenty-ninth";
        await Promise.resolve(twentyNinth);
        const thirtyFirst = twentyNinth + "-thirty-first";
        await Promise.resolve(thirtyFirst);
        const thirtySecond = thirtyFirst + "-thirty-second";
        await Promise.resolve(thirtySecond);
        const thirtyThird = thirtySecond + "-thirty-third";
        await Promise.resolve(thirtyThird);
        const thirtyFourth = thirtyThird + "-thirty-fourth";
        await Promise.resolve(thirtyFourth);
        const thirtyFifth = thirtyFourth + "-thirty-fifth";
        await Promise.resolve(thirtyFifth);
        const thirtySixth = thirtyFifth + "-thirty-sixth";
        await Promise.resolve(thirtySixth);
        const thirtySeventh = thirtySixth + "-thirty-seventh";
        await Promise.resolve(thirtySeventh);
        const thirtyEighth = thirtySeventh + "-thirty-eighth";
        await Promise.resolve(thirtyEighth);
        const thirtyNinth = thirtyEighth + "-thirty-ninth";
        await Promise.resolve(thirtyNinth);
        const fortieth = thirtyNinth + "-fortieth";
        await Promise.resolve(fortieth);
        const fortyFirst = fortieth + "-forty-first";
        await Promise.resolve(fortyFirst);
        const fortySecond = fortyFirst + "-forty-second";
        await Promise.resolve(fortySecond);
        const fortyThird = fortySecond + "-forty-third";
        await Promise.resolve(fortyThird);
        const fortyFourth = fortyThird + "-forty-fourth";
        await Promise.resolve(fortyFourth);
        const fortyFifth = fortyFourth + "-forty-fifth";
        await Promise.resolve(fortyFifth);
        const fortySixth = fortyFifth + "-forty-sixth";
        await Promise.resolve(fortySixth);
        const fortySeventh = fortySixth + "-forty-seventh";
        await Promise.resolve(fortySeventh);
        const fortyEighth = fortySeventh + "-forty-eighth";
        await Promise.resolve(fortyEighth);
        const fortyNinth = fortyEighth + "-forty-ninth";
        await Promise.resolve(fortyNinth);
        const fiftieth = fortyNinth + "-fiftieth";
        await Promise.resolve(fiftieth);
        const fiftyFirst = fiftieth + "-fifty-first";
        await Promise.resolve(fiftyFirst);
        const fiftySecond = fiftyFirst + "-fifty-second";
        await Promise.resolve(fiftySecond);
        const fiftyThird = fiftySecond + "-fifty-third";
        await Promise.resolve(fiftyThird);
        const fiftyFourth = fiftyThird + "-fifty-fourth";
        await Promise.resolve(fiftyFourth);
        const fiftyFifth = fiftyFourth + "-fifty-fifth";
        await Promise.resolve(fiftyFifth);
        const fiftySixth = fiftyFifth + "-fifty-sixth";
        await Promise.resolve(fiftySixth);
        const fiftySeventh = fiftySixth + "-fifty-seventh";
        await Promise.resolve(fiftySeventh);
        const fiftyEighth = fiftySeventh + "-fifty-eighth";
        await Promise.resolve(fiftyEighth);
        const fiftyNinth = fiftyEighth + "-fifty-ninth";
        await Promise.resolve(fiftyNinth);
        const sixtieth = fiftyNinth + "-sixtieth";
        await Promise.resolve(sixtieth);
        const sixtyFirst = sixtieth + "-sixty-first";
        await Promise.resolve(sixtyFirst);
        const sixtySecond = sixtyFirst + "-sixty-second";
        await Promise.resolve(sixtySecond);
        const sixtyThird = sixtySecond + "-sixty-third";
        await Promise.resolve(sixtyThird);
        const sixtyFourth = sixtyThird + "-sixty-fourth";
        await Promise.resolve(sixtyFourth);
        const sixtyFifth = sixtyFourth + "-sixty-fifth";
        await Promise.resolve(sixtyFifth);
        const sixtySixth = sixtyFifth + "-sixty-sixth";
        await Promise.resolve(sixtySixth);
        const sixtySeventh = sixtySixth + "-sixty-seventh";
        await Promise.resolve(sixtySeventh);
        const sixtyEighth = sixtySeventh + "-sixty-eighth";
        await Promise.resolve(sixtyEighth);
        const sixtyNinth = sixtyEighth + "-sixty-ninth";
        await Promise.resolve(sixtyNinth);
        const seventieth = sixtyNinth + "-seventieth";
        await Promise.resolve(seventieth);
        const seventyFirst = seventieth + "-seventy-first";
        await Promise.resolve(seventyFirst);
        const seventySecond = seventyFirst + "-seventy-second";
        await Promise.resolve(seventySecond);
        const seventyThird = seventySecond + "-seventy-third";
        await Promise.resolve(seventyThird);
        const seventyFourth = seventyThird + "-seventy-fourth";
        await Promise.resolve(seventyFourth);
        const seventyFifth = seventyFourth + "-seventy-fifth";
        await Promise.resolve(seventyFifth);
        const seventySixth = seventyFifth + "-seventy-sixth";
        await Promise.resolve(seventySixth);
        const seventySeventh = seventySixth + "-seventy-seventh";
        await Promise.resolve(seventySeventh);
        const seventyEighth = seventySeventh + "-seventy-eighth";
        await Promise.resolve(seventyEighth);
        const seventyNinth = seventyEighth + "-seventy-ninth";
        await Promise.resolve(seventyNinth);
        const eightieth = seventyNinth + "-eightieth";
        await Promise.resolve(eightieth);
        const eightyFirst = eightieth + "-eighty-first";
        await Promise.resolve(eightyFirst);
        const eightySecond = eightyFirst + "-eighty-second";
        await Promise.resolve(eightySecond);
        const eightyThird = eightySecond + "-eighty-third";
        await Promise.resolve(eightyThird);
        const eightyFourth = eightyThird + "-eighty-fourth";
        await Promise.resolve(eightyFourth);
        const eightyFifth = eightyFourth + "-eighty-fifth";
        await Promise.resolve(eightyFifth);
        const eightySixth = eightyFifth + "-eighty-sixth";
        await Promise.resolve(eightySixth);
        const eightySeventh = eightySixth + "-eighty-seventh";
        await Promise.resolve(eightySeventh);
        const eightyEighth = eightySeventh + "-eighty-eighth";
        await Promise.resolve(eightyEighth);
        const eightyNinth = eightyEighth + "-eighty-ninth";
        await Promise.resolve(eightyNinth);
        const ninetieth = eightyNinth + "-ninetieth";
        await Promise.resolve(ninetieth);
        const ninetyFirst = ninetieth + "-ninety-first";
        await Promise.resolve(ninetyFirst);
        const ninetySecond = ninetyFirst + "-ninety-second";
        await Promise.resolve(ninetySecond);
        const ninetyThird = ninetySecond + "-ninety-third";
        await Promise.resolve(ninetyThird);
        const ninetyFourth = ninetyThird + "-ninety-fourth";
        await Promise.resolve(ninetyFourth);
        const ninetyFifth = ninetyFourth + "-ninety-fifth";
        await Promise.resolve(ninetyFifth);
        const ninetySixth = ninetyFifth + "-ninety-sixth";
        await Promise.resolve(ninetySixth);
        const ninetySeventh = ninetySixth + "-ninety-seventh";
        await Promise.resolve(ninetySeventh);
        const ninetyEighth = ninetySeventh + "-ninety-eighth";
        await Promise.resolve(ninetyEighth);
        const ninetyNinth = ninetyEighth + "-ninety-ninth";
        await Promise.resolve(ninetyNinth);
        const oneHundredth = ninetyNinth + "-one-hundredth";
        await Promise.resolve(oneHundredth);
        const oneHundredFirst = oneHundredth + "-one-hundred-first";
        await Promise.resolve(oneHundredFirst);
        const oneHundredSecond = oneHundredFirst + "-one-hundred-second";
        await Promise.resolve(oneHundredSecond);
        const oneHundredThird = oneHundredSecond + "-one-hundred-third";
        await Promise.resolve(oneHundredThird);
        const oneHundredFourth = oneHundredThird + "-one-hundred-fourth";
        await Promise.resolve(oneHundredFourth);
        const oneHundredFifth = oneHundredFourth + "-one-hundred-fifth";
        await Promise.resolve(oneHundredFifth);
        const oneHundredSixth = oneHundredFifth + "-one-hundred-sixth";
        await Promise.resolve(oneHundredSixth);
        const oneHundredSeventh = oneHundredSixth + "-one-hundred-seventh";
        await Promise.resolve(oneHundredSeventh);
        const oneHundredEighth = oneHundredSeventh + "-one-hundred-eighth";
        await Promise.resolve(oneHundredEighth);
        const oneHundredNinth = oneHundredEighth + "-one-hundred-ninth";
        await Promise.resolve(oneHundredNinth);
        const oneHundredTenth = oneHundredNinth + "-one-hundred-tenth";
        await Promise.resolve(oneHundredTenth);
        const oneHundredEleventh = oneHundredTenth + "-one-hundred-eleventh";
        await Promise.resolve(oneHundredEleventh);
        const oneHundredTwelfth = oneHundredEleventh + "-one-hundred-twelfth";
        await Promise.resolve(oneHundredTwelfth);
        const oneHundredThirteenth = oneHundredTwelfth + "-one-hundred-thirteenth";
        await Promise.resolve(oneHundredThirteenth);
        const oneHundredFourteenth = oneHundredThirteenth + "-one-hundred-fourteenth";
        await Promise.resolve(oneHundredFourteenth);
        const oneHundredFifteenth = oneHundredFourteenth + "-one-hundred-fifteenth";
        await Promise.resolve(oneHundredFifteenth);
        output.push(oneHundredFifteenth);
        break;
    }
    return output.join(",");
}

const emitter = new EventEmitter();
const iterator: any = on(emitter, "data");
collect(iterator, []).then((value: string): void => {
    console.log("body-one-hundred-fifteen-awaits:", value);
});
emitter.emit("data", "item");
