const proto: any = Array.prototype;
const ctor: any = proto.constructor;
const descriptor: any = Object.getOwnPropertyDescriptor(proto, "constructor");
const speciesDescriptor: any = Object.getOwnPropertyDescriptor(Array, Symbol.species);
const constructorSymbols: symbol[] = Object.getOwnPropertySymbols(Array);
const ownNames: string[] = Object.getOwnPropertyNames(Array);
const isArrayDescriptor: any = Object.getOwnPropertyDescriptor(Array, "isArray");
const fromDescriptor: any = Object.getOwnPropertyDescriptor(Array, "from");
const ofDescriptor: any = Object.getOwnPropertyDescriptor(Array, "of");
const detachedIsArray: any = Array.isArray;
const detachedFrom: any = Array.from;
const detachedOf: any = Array.of;
const called: any = ctor("a", "b");
const sized: any = Array(3);
const constructed: any = new Array("x", "y");
const detachedSource: any = JSON.parse("[\"p\",\"q\"]");
const detachedCopy: any = detachedFrom(detachedSource);
const detachedMapped: any = detachedFrom(detachedSource, function (this: any, value: any, index: number): string {
    return this.prefix + index + value;
}, { prefix: "m" });
const detachedMade: any = detachedOf("u", "v");

console.log("identity:", ctor === Array, ctor.prototype === proto, descriptor.writable, descriptor.enumerable, descriptor.configurable, typeof ctor, ctor.name, ctor.length);
console.log("species:", Array[Symbol.species] === Array, typeof speciesDescriptor.get, speciesDescriptor.set === undefined, speciesDescriptor.enumerable, speciesDescriptor.configurable, constructorSymbols.length, constructorSymbols[0] === Symbol.species);
console.log("static names:", ownNames.includes("isArray"), ownNames.includes("from"), ownNames.includes("of"), ownNames.includes("__tsc_symbol_species"));
console.log("static desc:", isArrayDescriptor.value === Array.isArray, isArrayDescriptor.value.name, isArrayDescriptor.value.length, isArrayDescriptor.writable, isArrayDescriptor.enumerable, isArrayDescriptor.configurable);
console.log("from/of desc:", fromDescriptor.value === Array.from, fromDescriptor.value.name, fromDescriptor.value.length, ofDescriptor.value === Array.of, ofDescriptor.value.name, ofDescriptor.value.length);
console.log("detached static:", detachedIsArray([]), detachedIsArray({}), detachedCopy.join("|"), detachedMapped.join("|"), detachedMade.join("|"));
console.log("call:", Array.isArray(called), called.length, called[0], called[1]);
console.log("size:", sized.length, sized[0] === undefined, sized[2] === undefined);
console.log("new:", Array.isArray(constructed), constructed.length, constructed[0], constructed[1]);
